language: node_js
addons:
    code_climate:
        repo_token: 62b74b9f426f9a51919f010b1297c76150d97f1b4a0f5dcbefeb5c644b25c963
node_js:
  - "8"
  - "10"

install:
  - npm install

before_script:
  - npm install -g mocha
	- "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script: 
  - fossa init
  - fossa analyze

after_success:
  - npm run cover
  - codeclimate-test-reporter < coverage/lcov.info
  - fossa test
