language: node_js
addons:
  code_climate:
      repo_token: 62b74b9f426f9a51919f010b1297c76150d97f1b4a0f5dcbefeb5c644b25c963
node_js:
  - "8"
  - "10"
  - "11"
  - "12"

install:
  - npm install

before_script:
  - npm install -g mocha

after_success:
  - npm run cover
  - codeclimate-test-reporter < coverage/lcov.info
  - fossa test
